### ISSUE TITLE
BUG: App sticks on dock

### ISSUE THREAD

**Issue by mariogarridopt** [flaviodelgrosso/chatgpt-tray-app#3]
I like the way the app is kept on the tray but there is no reason to keep it on the dock at the same time.

## Bug
The app stays on the dock

It looks like this is not the intended behavior because app.ts has the code:

```ts
if (process.platform === 'darwin') {
  app.setActivationPolicy('accessory');
  app.dock.hide();
}
```

Because of a bug on Electron ` app.dock.hide();` is not working: https://github.com/electron/electron/issues/16093

A solution has been submitted to Electron using `app.setActivationPolicy()`:  https://github.com/electron/electron/pull/21983

Docs about `setActivationPolicy` are available here: https://www.electronjs.org/docs/latest/api/app#appsetactivationpolicypolicy-macos

**Comment by mariogarridopt** [comment]
Gitify had a weird way to go around this issue: https://github.com/manosim/gitify/blob/f8a6ac26c5a58d17f9c2eb639489b045aec1a780/main.js#L29-L37

But it works on this app too... (#4 )

**Comment by flaviodelgrosso** [comment]
> I like the way the app is kept on the tray but there is no reason to keep it on the dock at the same time.
> 
> ## Bug
> The app stays on the dock
> 
> It looks like this is not the intended behavior because app.ts has the code:
> 
> ```ts
> if (process.platform === 'darwin') {
>   app.setActivationPolicy('accessory');
>   app.dock.hide();
> }
> ```
> 
> Because of a bug on Electron ` app.dock.hide();` is not working: [electron/electron#16093](https://github.com/electron/electron/issues/16093)
> 
> A solution has been submitted to Electron using `app.setActivationPolicy()`: [electron/electron#21983](https://github.com/electron/electron/pull/21983)
> 
> Docs about `setActivationPolicy` are available here: https://www.electronjs.org/docs/latest/api/app#appsetactivationpolicypolicy-macos



Hi @mariogarridopt, thanks for opening a PR, I appreciate it. 
Yes, actually there's this annoying bug and I didn't invested too much time about it. However, it's ok to merge this workaround at the moment. I'll add a little comment about this issue.
